//Action Types
export const SET_DEGREE = "SET_DEGREE";
export const SET_SCALE = "SET_SCALE";
export const SET_OPACITY = "SET_OPACITY";
export const SET_SEARCH_BOX_WIDTH = "SET_SEARCH_BOX_WIDTH";
export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const SET_BORDER_RADIUS = "SET_BORDER_RADIUS";
export const SET_TOP_DISTANCE = "SET_TOP_DISTANCE";
export const RESET_GENE_LIST = "RESET_GENE_LIST";
export const RECEIVE_GENE_LIST = "RECEIVE_GENE_LIST";
export const RESET_VARIANT_LIST = "RESET_VARIANT_LIST";
export const RECEIVE_VARIANT_LIST = "RECEIVE_VARIANT_LIST";
export const SET_EXPANDED = "SET_EXPANDED";
