# Generated by Django 2.0 on 2018-01-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='name',
        ),
        migrations.AddField(
            model_name='variant',
            name='accession',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='alias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='assembly',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='chrx',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='genomic_start',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='genomic_stop',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='inferred_classification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='last_evaluated',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='last_updated',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='nucleotide_change',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='other_mappings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='protein_change',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='reported_alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='reported_classification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='reported_ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='submitter_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='transcripts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='gene',
            field=models.CharField(max_length=200),
        ),
    ]
