# Generated by Django 2.0 on 2018-01-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0002_auto_20180106_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneVariantResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.TextField(blank=True, db_column='Gene', null=True)),
                ('nucleotide_change', models.TextField(blank=True, db_column='Nucleotide Change', null=True)),
                ('protein_change', models.TextField(blank=True, db_column='Protein Change', null=True)),
                ('other_mappings', models.TextField(blank=True, db_column='Other Mappings', null=True)),
                ('alias', models.TextField(blank=True, db_column='Alias', null=True)),
                ('transcripts', models.TextField(blank=True, db_column='Transcripts', null=True)),
                ('region', models.TextField(blank=True, db_column='Region', null=True)),
                ('reported_classification', models.TextField(blank=True, db_column='Reported Classification', null=True)),
                ('inferred_classification', models.TextField(blank=True, db_column='Inferred Classification', null=True)),
                ('source', models.TextField(blank=True, db_column='Source', null=True)),
                ('last_evaluated', models.TextField(blank=True, db_column='Last Evaluated', null=True)),
                ('last_updated', models.TextField(blank=True, db_column='Last Updated', null=True)),
                ('url', models.TextField(blank=True, db_column='URL', null=True)),
                ('submitter_comment', models.TextField(blank=True, db_column='Submitter Comment', null=True)),
                ('assembly', models.TextField(blank=True, db_column='Assembly', null=True)),
                ('chr', models.TextField(blank=True, db_column='Chr', null=True)),
                ('genomic_start', models.TextField(blank=True, db_column='Genomic Start', null=True)),
                ('genomic_stop', models.TextField(blank=True, db_column='Genomic Stop', null=True)),
                ('ref', models.TextField(blank=True, db_column='Ref', null=True)),
                ('alt', models.TextField(blank=True, db_column='Alt', null=True)),
                ('accession', models.TextField(blank=True, db_column='Accession', null=True)),
                ('reported_ref', models.TextField(blank=True, db_column='Reported Ref', null=True)),
                ('reported_alt', models.TextField(blank=True, db_column='Reported Alt', null=True)),
            ],
            options={
                'db_table': 'gene_variant_results',
                'managed': False,
            },
        ),
    ]
