# Generated by Django 2.0 on 2018-01-07 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0003_genevariantresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='accession',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='assembly',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='chrx',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='genomic_start',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='genomic_stop',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='inferred_classification',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='last_evaluated',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='nucleotide_change',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='other_mappings',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='protein_change',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='region',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='reported_alt',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='reported_classification',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='reported_ref',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='source',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='submitter_comment',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='transcripts',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='url',
        ),
    ]
