# Generated by Django 2.0 on 2018-01-07 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0004_auto_20180107_2107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
