# Generated by Django 2.0 on 2018-01-07 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0006_variantresults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variantresults',
            options={},
        ),
    ]
