# Generated by Django 2.0 on 2018-01-07 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0007_auto_20180107_2139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariantResults',
            new_name='Variant_Results',
        ),
        migrations.AlterModelTable(
            name='variant_results',
            table=None,
        ),
    ]
